<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUnm5aam\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUnm5aam/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUnm5aam.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUnm5aam\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUnm5aam\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Unm5aam',
    'container.build_id' => '85d4d7c0',
    'container.build_time' => 1525428269,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUnm5aam');
