<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerFos3xea\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFos3xea/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFos3xea.legacy');
=======
if (\class_exists(\ContainerW7cvg7g\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW7cvg7g/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerW7cvg7g.legacy');
>>>>>>> 0778aab4bee984492047322f575da86c34e4d02b

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerFos3xea\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFos3xea\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fos3xea',
    'container.build_id' => 'c19bbdaf',
    'container.build_time' => 1525882880,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFos3xea');
=======
    \class_alias(\ContainerW7cvg7g\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerW7cvg7g\appDevDebugProjectContainer(array(
    'container.build_hash' => 'W7cvg7g',
    'container.build_id' => '8aec6978',
    'container.build_time' => 1526040796,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerW7cvg7g');
>>>>>>> 0778aab4bee984492047322f575da86c34e4d02b
