<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPv5ciwi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPv5ciwi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPv5ciwi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPv5ciwi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPv5ciwi\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pv5ciwi',
    'container.build_id' => '0fd2ba75',
    'container.build_time' => 1525365956,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPv5ciwi');
