<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerItxwh9z\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerItxwh9z/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerItxwh9z.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerItxwh9z\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerItxwh9z\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Itxwh9z',
    'container.build_id' => '58eb3046',
    'container.build_time' => 1525353706,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerItxwh9z');
